# Generated by Django 3.2.7 on 2023-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_car_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CO', 'Convertible'), ('T', 'Transporter'), ('C', 'Compact'), ('V', 'Van'), ('O', 'Other'), ('SE', 'Sedan'), ('CU', 'Coupe'), ('S', 'SUV'), ('SW', 'Station wagon ')], max_length=255),
        ),
    ]
