# Generated by Django 3.2.7 on 2023-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231213_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('L', 'LPG'), ('G', 'Gasoline'), ('D', 'Diesel'), ('E', 'Electric')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('SE', 'Sedan'), ('O', 'Other'), ('V', 'Van'), ('SW', 'Station wagon '), ('S', 'SUV'), ('T', 'Transporter'), ('CO', 'Convertible'), ('C', 'Compact'), ('CU', 'Coupe')], max_length=255),
        ),
    ]
