# Generated by Django 3.2.7 on 2023-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20231213_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CO', 'Convertible'), ('V', 'Van'), ('SW', 'Station wagon '), ('SE', 'Sedan'), ('C', 'Compact'), ('CU', 'Coupe'), ('S', 'SUV'), ('T', 'Transporter'), ('O', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('E', 'Electric'), ('G', 'Gasoline'), ('L', 'LPG'), ('D', 'Diesel')], default='None', max_length=255),
        ),
    ]
