# Generated by Django 3.2.7 on 2023-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20231213_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('V', 'Van'), ('C', 'Compact'), ('O', 'Other'), ('SE', 'Sedan'), ('CU', 'Coupe'), ('S', 'SUV'), ('T', 'Transporter'), ('CO', 'Convertible'), ('SW', 'Station wagon ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='default_car.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Gasoline'), ('L', 'LPG'), ('E', 'Electric'), ('D', 'Diesel')], default='None', max_length=255),
        ),
    ]
