# Generated by Django 3.2.7 on 2023-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20231214_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CO', 'Convertible'), ('SE', 'Sedan'), ('C', 'Compact'), ('T', 'Transporter'), ('SW', 'Station wagon '), ('V', 'Van'), ('CU', 'Coupe'), ('S', 'SUV'), ('O', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='default_car.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('E', 'Electric'), ('G', 'Gasoline'), ('L', 'LPG')], default='None', max_length=255),
        ),
    ]
