# Generated by Django 3.2.7 on 2023-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20231216_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('S', 'SUV'), ('C', 'Compact'), ('CO', 'Convertible'), ('CU', 'Coupe'), ('SW', 'Station wagon '), ('V', 'Van'), ('O', 'Other'), ('SE', 'Sedan'), ('T', 'Transporter')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('E', 'Electric'), ('G', 'Gasoline'), ('L', 'LPG')], default='None', max_length=255),
        ),
    ]
