# Generated by Django 3.2.7 on 2023-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20231216_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Compact', 'Compact'), ('Transporter', 'Transporter'), ('Station wagon', 'Station wagon '), ('Van', 'Van'), ('Convertible', 'Convertible'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=255),
        ),
    ]
