# Generated by Django 3.2.7 on 2023-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20231216_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Compact', 'Compact'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Van', 'Van'), ('Station wagon', 'Station wagon '), ('Transporter', 'Transporter'), ('Other', 'Other'), ('Sedan', 'Sedan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=255),
        ),
    ]
