# Generated by Django 3.2.7 on 2023-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20231216_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Van', 'Van'), ('Transporter', 'Transporter'), ('Sedan', 'Sedan'), ('Other', 'Other'), ('SUV', 'SUV'), ('Compact', 'Compact'), ('Convertible', 'Convertible'), ('Station wagon', 'Station wagon ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('LPG', 'LPG'), ('Electric', 'Electric')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None, max_length=255),
        ),
    ]
