# Generated by Django 3.2.7 on 2023-12-13 20:20

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('body', models.CharField(choices=[('S', 'SUV'), ('CU', 'Coupe'), ('SW', 'Station wagon '), ('CO', 'Convertible'), ('V', 'Van'), ('C', 'Compact'), ('O', 'Other'), ('SE', 'Sedan'), ('T', 'Transporter')], max_length=255)),
                ('first_registration', models.IntegerField(validators=[base.models.validate_registration_year])),
            ],
        ),
    ]
