# Generated by Django 3.2.7 on 2023-12-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='first_registration',
            new_name='first_registration_year',
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('V', 'Van'), ('O', 'Other'), ('SW', 'Station wagon '), ('T', 'Transporter'), ('S', 'SUV'), ('CO', 'Convertible'), ('CU', 'Coupe'), ('SE', 'Sedan'), ('C', 'Compact')], max_length=255),
        ),
    ]
