# Generated by Django 3.2.7 on 2023-12-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231213_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CU', 'Coupe'), ('CO', 'Convertible'), ('O', 'Other'), ('C', 'Compact'), ('V', 'Van'), ('SE', 'Sedan'), ('S', 'SUV'), ('T', 'Transporter'), ('SW', 'Station wagon ')], max_length=255),
        ),
    ]
