# Generated by Django 3.2.7 on 2023-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20231213_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('SW', 'Station wagon '), ('T', 'Transporter'), ('S', 'SUV'), ('O', 'Other'), ('CO', 'Convertible'), ('C', 'Compact'), ('SE', 'Sedan'), ('CU', 'Coupe'), ('V', 'Van')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('E', 'Electric'), ('L', 'LPG'), ('D', 'Diesel'), ('G', 'Gasoline')], default='None', max_length=255),
        ),
    ]
