# Generated by Django 3.2.7 on 2023-12-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('V', 'Van'), ('T', 'Transporter'), ('SE', 'Sedan'), ('O', 'Other'), ('SW', 'Station wagon '), ('S', 'SUV'), ('C', 'Compact'), ('CO', 'Convertible'), ('CU', 'Coupe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='road.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('E', 'Electric'), ('D', 'Diesel'), ('G', 'Gasoline'), ('L', 'LPG')], default='None', max_length=255),
        ),
    ]
