# Generated by Django 3.2.7 on 2023-12-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20231213_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CU', 'Coupe'), ('CO', 'Convertible'), ('S', 'SUV'), ('T', 'Transporter'), ('O', 'Other'), ('SE', 'Sedan'), ('V', 'Van'), ('SW', 'Station wagon '), ('C', 'Compact')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='default_car', upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('E', 'Electric'), ('L', 'LPG')], default='None', max_length=255),
        ),
    ]
