# Generated by Django 3.2.7 on 2023-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20231214_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('CO', 'Convertible'), ('C', 'Compact'), ('SW', 'Station wagon '), ('CU', 'Coupe'), ('V', 'Van'), ('O', 'Other'), ('S', 'SUV'), ('SE', 'Sedan'), ('T', 'Transporter')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('L', 'LPG'), ('E', 'Electric'), ('G', 'Gasoline'), ('D', 'Diesel')], default='None', max_length=255),
        ),
    ]
