# Generated by Django 3.2.7 on 2023-12-16 13:25

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20231216_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Transporter', 'Transporter'), ('Compact', 'Compact'), ('Van', 'Van'), ('SUV', 'SUV'), ('Station wagon', 'Station wagon '), ('Convertible', 'Convertible'), ('Other', 'Other'), ('Sedan', 'Sedan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_registration_year',
            field=models.IntegerField(default=2023, validators=[base.models.validate_registration_year]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('LPG', 'LPG'), ('Diesel', 'Diesel')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car_brands'),
        ),
    ]
