# Generated by Django 3.2.7 on 2023-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20231216_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Station wagon', 'Station wagon '), ('Transporter', 'Transporter'), ('Other', 'Other'), ('Van', 'Van'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Compact', 'Compact')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Electric', 'Electric'), ('LPG', 'LPG'), ('Diesel', 'Diesel')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None, max_length=255),
        ),
    ]
