# Generated by Django 3.2.7 on 2023-12-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20231216_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='car_brand',
            old_name='name',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Transporter', 'Transporter'), ('Station wagon', 'Station wagon '), ('Coupe', 'Coupe'), ('Compact', 'Compact'), ('Other', 'Other'), ('Van', 'Van'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Gasoline', 'Gasoline'), ('Electric', 'Electric'), ('Diesel', 'Diesel')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car_model'),
        ),
    ]
