# Generated by Django 3.2.7 on 2023-12-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20231216_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Compact', 'Compact'), ('Sedan', 'Sedan'), ('Transporter', 'Transporter'), ('Other', 'Other'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Station wagon', 'Station wagon ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel')], default='None', max_length=255),
        ),
    ]
