# Generated by Django 3.2.7 on 2023-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20231218_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Compact', 'Compact'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('Station wagon', 'Station wagon '), ('Other', 'Other'), ('Transporter', 'Transporter'), ('Sedan', 'Sedan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Gasoline', 'Gasoline'), ('Electric', 'Electric')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=255),
        ),
    ]
