# Generated by Django 3.2.7 on 2023-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20231219_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Station wagon', 'Station wagon'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Transporter', 'Transporter'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Electric', 'Electric')], default='None', max_length=255),
        ),
    ]
