# Generated by Django 3.2.7 on 2023-12-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20231226_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='contact_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
