# Generated by Django 3.2.7 on 2023-12-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20231226_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
