# Generated by Django 3.2.7 on 2023-12-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_car_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Abarth ', 'Abarth '), ('Alfa Romeo', 'Convertible'), ('Aston Martin', 'Coupe'), ('Audi', 'SUV'), ('Bentley', 'Station wagon'), ('BMW', 'Sedan'), ('Cadillac', 'Van'), ('Citroen', 'Transporter'), ('Dacia', 'Other'), ('Dodge ', 'Abarth '), ('Ferrari', 'Convertible'), ('Fiat', 'Coupe'), ('Ford', 'SUV'), ('GMC', 'Station wagon'), ('Honda', 'Sedan'), ('Hundai', 'Van'), ('Infiniti', 'Transporter'), ('Jaguar', 'Other'), ('Jeep ', 'Abarth '), ('Kia', 'Convertible'), ('Lamborghini', 'Coupe'), ('Lancia', 'SUV'), ('Land Rover', 'Station wagon'), ('Lexus', 'Sedan'), ('Lotus', 'Van'), ('Maserati', 'Transporter'), ('Mazda', 'Other'), ('Mercedes-Benz ', 'Abarth '), ('Mitsubishi', 'Convertible'), ('Nissan', 'Coupe'), ('Opel', 'SUV'), ('Peugeot', 'Station wagon'), ('Porsche', 'Sedan'), ('Ram', 'Van'), ('Renault', 'Transporter'), ('Seat', 'Other'), ('Skoda', 'Other'), ('Subaru ', 'Abarth '), ('Suzuki', 'Convertible'), ('Tesla', 'Coupe'), ('Toyota', 'SUV'), ('Volkswagen', 'Station wagon'), ('Volvo', 'Sedan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Car_Brand',
        ),
        migrations.DeleteModel(
            name='Car_Model',
        ),
    ]
