# Generated by Django 3.2.7 on 2023-12-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20231226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Station wagon', 'Station wagon'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Transporter', 'Transporter'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Car_Brand',
        ),
        migrations.DeleteModel(
            name='Car_Model',
        ),
    ]
